name: Playground repository snapshot

permissions: {}

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  snapshot:
    runs-on: ubuntu-latest

    permissions:
      id-token: 'write' # for OIDC identity access
      contents: 'write' # for commiting snapshot/timestamp changes

    outputs:
      generated: ${{ steps.snapshot.outputs.generated }}

    steps:
      - id: snapshot
        uses: jku/repository-playground/playground/actions/snapshot@main
        with:
          gcp_workload_identity_provider: ${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: ${{ vars.GCP_SERVICE_ACCOUNT }}

  deploy:
    permissions:
      pages: write
      id-token: write # for authenticating to GH Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: snapshot
    if: needs.snapshot.outputs.generated == 'true'
    steps:
      - name: Deploy Playground repository to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@0243b6c10d06cb8e95ed8ee471231877621202c0
